# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
#sudo: false
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libjq-dev
      - valgrind
      - libv8-3.14-dev
      - libudunits2-dev
      - libprotobuf-dev
      - protobuf-compiler


r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'
