# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
cache: packages

script:
  - |
    R CMD build .
    travis_wait 30 R CMD check fingertipsR*tar.gz

apt_packages:
  - libudunits2-dev
  - libv8-dev
  - libprotobuf-dev
  - libprotoc-dev
  - protobuf-compiler
  - valgrind

before_install:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev netcdf-bin libv8-dev libjq-dev libprotobuf-dev

compiler:
  - clang

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

r_github_packages:
  - r-lib/vdiffr # Install manually because dev vdiffr is not compatible with Appveyor yet
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'
